import ProductGrid from "./RecommendedProductGrid";
const productGrid = [
  {
    img: "assets/images/thumbs/product-img7.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img8.png",
    title: "Marcel's Modern Pantry Almond Unsweetened",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img9.png",
    title: "O Organics Milk, Whole, Vitamin D",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img10.png",
    title: "Whole Grains and Seeds Organic Bread",
    badge: "Best Sale",
    badgeClass: "bg-info-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img11.png",
    title: "Lucerne Yogurt, Lowfat, Strawberry",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img12.png",
    title: "Nature Valley Whole Grain Oats and Honey Protein",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img13.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img14.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img15.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: "New",
    badgeClass: "bg-warning-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img16.png",
    title: "Good & Gather Farmed Atlantic Salmon",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img17.png",
    title: "Market Pantry 41/50 Raw Tail-Off Large Raw Shrimp",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img18.png",
    title: "Tropicana 100% Juice, Orange, No Pulp",
    badge: "New",
    badgeClass: "bg-warning-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
];
const productsSection1 = [
  {
    img: "assets/images/thumbs/product-img7.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img8.png",
    title: "Marcel's Modern Pantry Almond Unsweetened",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img9.png",
    title: "O Organics Milk, Whole, Vitamin D",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img10.png",
    title: "Whole Grains and Seeds Organic Bread",
    badge: "Best Sale",
    badgeClass: "bg-info-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img11.png",
    title: "Lucerne Yogurt, Lowfat, Strawberry",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img12.png",
    title: "Nature Valley Whole Grain Oats and Honey Protein",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img13.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img14.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img15.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: "New",
    badgeClass: "bg-warning-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img16.png",
    title: "Good & Gather Farmed Atlantic Salmon",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img17.png",
    title: "Market Pantry 41/50 Raw Tail-Off Large Raw Shrimp",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img18.png",
    title: "Tropicana 100% Juice, Orange, No Pulp",
    badge: "New",
    badgeClass: "bg-warning-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
];

const productsSection2 = [
  {
    img: "assets/images/thumbs/product-img7.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img8.png",
    title: "Marcel's Modern Pantry Almond Unsweetened",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img9.png",
    title: "O Organics Milk, Whole, Vitamin D",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img10.png",
    title: "Whole Grains and Seeds Organic Bread",
    badge: "Best Sale",
    badgeClass: "bg-info-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img11.png",
    title: "Lucerne Yogurt, Lowfat, Strawberry",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img12.png",
    title: "Nature Valley Whole Grain Oats and Honey Protein",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img13.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img14.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img15.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: "New",
    badgeClass: "bg-warning-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img16.png",
    title: "Good & Gather Farmed Atlantic Salmon",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img17.png",
    title: "Market Pantry 41/50 Raw Tail-Off Large Raw Shrimp",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img18.png",
    title: "Tropicana 100% Juice, Orange, No Pulp",
    badge: "New",
    badgeClass: "bg-warning-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
];
const productsSection3 = [
  {
    img: "assets/images/thumbs/product-img7.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img8.png",
    title: "Marcel's Modern Pantry Almond Unsweetened",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img9.png",
    title: "O Organics Milk, Whole, Vitamin D",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img10.png",
    title: "Whole Grains and Seeds Organic Bread",
    badge: "Best Sale",
    badgeClass: "bg-info-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img11.png",
    title: "Lucerne Yogurt, Lowfat, Strawberry",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img12.png",
    title: "Nature Valley Whole Grain Oats and Honey Protein",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img13.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img14.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img15.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: "New",
    badgeClass: "bg-warning-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img16.png",
    title: "Good & Gather Farmed Atlantic Salmon",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img17.png",
    title: "Market Pantry 41/50 Raw Tail-Off Large Raw Shrimp",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img18.png",
    title: "Tropicana 100% Juice, Orange, No Pulp",
    badge: "New",
    badgeClass: "bg-warning-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
];
const productsSection4 = [
  {
    img: "assets/images/thumbs/product-img7.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img8.png",
    title: "Marcel's Modern Pantry Almond Unsweetened",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img9.png",
    title: "O Organics Milk, Whole, Vitamin D",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img10.png",
    title: "Whole Grains and Seeds Organic Bread",
    badge: "Best Sale",
    badgeClass: "bg-info-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img11.png",
    title: "Lucerne Yogurt, Lowfat, Strawberry",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img12.png",
    title: "Nature Valley Whole Grain Oats and Honey Protein",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img13.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img14.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img15.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: "New",
    badgeClass: "bg-warning-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img16.png",
    title: "Good & Gather Farmed Atlantic Salmon",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img17.png",
    title: "Market Pantry 41/50 Raw Tail-Off Large Raw Shrimp",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img18.png",
    title: "Tropicana 100% Juice, Orange, No Pulp",
    badge: "New",
    badgeClass: "bg-warning-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
];
const productsSection5 = [
  {
    img: "assets/images/thumbs/product-img7.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img8.png",
    title: "Marcel's Modern Pantry Almond Unsweetened",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img9.png",
    title: "O Organics Milk, Whole, Vitamin D",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img10.png",
    title: "Whole Grains and Seeds Organic Bread",
    badge: "Best Sale",
    badgeClass: "bg-info-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img11.png",
    title: "Lucerne Yogurt, Lowfat, Strawberry",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img12.png",
    title: "Nature Valley Whole Grain Oats and Honey Protein",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img13.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: null,
    badgeClass: "",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img14.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img15.png",
    title: "C-500 Antioxidant Protect Dietary Supplement",
    badge: "New",
    badgeClass: "bg-warning-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img16.png",
    title: "Good & Gather Farmed Atlantic Salmon",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img17.png",
    title: "Market Pantry 41/50 Raw Tail-Off Large Raw Shrimp",
    badge: "Sale 50%",
    badgeClass: "bg-danger-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
  {
    img: "assets/images/thumbs/product-img18.png",
    title: "Tropicana 100% Juice, Orange, No Pulp",
    badge: "New",
    badgeClass: "bg-warning-600",
    store: "Lucky Supermarket",
    price: 14.99,
    oldPrice: 28.99,
    rating: 4.8,
    reviews: "17k",
  },
];

const RecommendedOne = () => (
  <section className="recommended">
    <div className="container container-lg">
      {/* ...tab headings... */}
      <div className="tab-content" id="pills-tabContent">
        <div
          className="tab-pane fade show active"
          id="pills-all"
          role="tabpanel"
          aria-labelledby="pills-all-tab"
          tabIndex={0}
        >
          <ProductGrid products={productGrid} />
        </div>
        <div
          className="tab-pane fade"
          id="pills-grocery"
          role="tabpanel"
          aria-labelledby="pills-grocery-tab"
          tabIndex={0}
        >
          <ProductGrid products={productsSection2} />
        </div>
        <div
          className="tab-pane fade"
          id="pills-fruits"
          role="tabpanel"
          aria-labelledby="pills-fruits-tab"
          tabIndex={0}
        >
          <ProductGrid products={productsSection1} />
        </div>
        <div
          className="tab-pane fade"
          id="pills-juices"
          role="tabpanel"
          aria-labelledby="pills-juices-tab"
          tabIndex={0}
        >
          <ProductGrid products={productsSection1} />
        </div>
        <div
          className="tab-pane fade"
          id="pills-vegetables"
          role="tabpanel"
          aria-labelledby="pills-vegetables-tab"
          tabIndex={0}
        >
          <ProductGrid products={productsSection3} />
        </div>
        <div
          className="tab-pane fade"
          id="pills-snacks"
          role="tabpanel"
          aria-labelledby="pills-snacks-tab"
          tabIndex={0}
        >
          <ProductGrid products={productsSection4} />
        </div>
        <div
          className="tab-pane fade"
          id="pills-organic"
          role="tabpanel"
          aria-labelledby="pills-organic-tab"
          tabIndex={0}
        >
          <ProductGrid products={productsSection5} />
        </div>
      </div>
    </div>
  </section>
);

export default RecommendedOne;
